version: "3.8"

# Services
services:
  # PostgreSQL база данных
  db:
    image: postgres:15-alpine
    container_name: registration_db
    environment:
      POSTGRES_DB: registration_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: registration_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/registration_db
      CORS_ORIGINS: '["http://127.0.0.1:3000","http://localhost:3000"]'
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
        sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: registration_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
